CREATE SCHEMA `recipes_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;

CREATE TABLE `RECIPES` (
  `RECIPE_ID` int NOT NULL AUTO_INCREMENT,
  `RECIPE_TITLE` varchar(250) NOT NULL,
  `RECIPE_IMAGE` varchar(50) DEFAULT NULL,
  `COOKING_TIME` varchar(50) DEFAULT NULL,
  `PORTION_AMOUNT` varchar(10) DEFAULT NULL,
  `RECIPE_DESCRIPTION` varchar(2000) DEFAULT NULL,
  `RECIPE_ADVICE` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`RECIPE_ID`),
  UNIQUE KEY `RECIPE_TITLE` (`RECIPE_TITLE`,`COOKING_TIME`,`PORTION_AMOUNT`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `INGREDIENTS` (
  `INGREDIENT_ID` int NOT NULL AUTO_INCREMENT,
  `RECIPE_ID` int NOT NULL,
  `INGREDIENT_DESCRIPTION` varchar(250) DEFAULT NULL,
  `INGREDIENT_AMOUNT` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`INGREDIENT_ID`),
  KEY `FK_INGREDIENT_RECIPE_ID` (`RECIPE_ID`),
  CONSTRAINT `FK_INGREDIENT_RECIPE_ID` FOREIGN KEY (`RECIPE_ID`) REFERENCES `RECIPES` (`RECIPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RECIPE_INSTRUCTIONS` (
  `STEP_ID` int NOT NULL AUTO_INCREMENT,
  `STEP_NUMBER` int NOT NULL,
  `RECIPE_ID` int NOT NULL,
  `STEP_IMAGE` varchar(50) DEFAULT NULL,
  `STEP_DESCRIPTION` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`STEP_ID`),
  KEY `FK_RECIPE_ID` (`RECIPE_ID`),
  CONSTRAINT `FK_RECIPE_ID` FOREIGN KEY (`RECIPE_ID`) REFERENCES `RECIPES` (`RECIPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RECIPE_TAGS` (
  `TAG_ID` int NOT NULL AUTO_INCREMENT,
  `RECIPE_ID` int NOT NULL,
  `TAG_DESCRIPTION` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`TAG_ID`),
  KEY `FK_TAG_RECIPE_ID` (`RECIPE_ID`),
  CONSTRAINT `FK_TAG_RECIPE_ID` FOREIGN KEY (`RECIPE_ID`) REFERENCES `RECIPES` (`RECIPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;